name: bbwade
favicon: null
layout_spectrum: 0.5433362580370158
typography_spectrum: 0.6199757000431418
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7646207143552601
  lightness: 0.03611396253108978
  saturation: 0.9104368803091347
  rhythmicContrast: 0.3140510874800384
purpose: []
